### ISSUE TITLE
用户日记页面的一个小问题,在查看其它用户撰写的日记时,会直接进入编辑页面

### ISSUE THREAD

**Issue by siosr** [LittleChai/littlechai_diary2.0#1]
async toEditDiary(e) {
    let id = e.currentTarget.dataset.id;
    let openid = e.currentTarget.dataset.openid;
    console.log(e)
    if(openid === wx.getStorageSync('openid')) {
    wx.navigateTo({
      url: '/pages/editDiary/editDiary?id='+id, //是本人就进入编辑
    })
  }else{
    wx.navigateTo({
      url: '/pages/diaryDetail/diaryDetail?id='+id, //不是本人就进入查看
    })
  }
  },

**Comment by KyaukYou** [comment]
已经解决
